### ISSUE TITLE
Allow other units and even calc()

### ISSUE THREAD

**Issue by nhoizey** [JeremiePat/grids-and-rulers#2]
My body font size is responsive:

```css
body {
  font-size: calc(0.9rem + 0.5vw);
  line-heigth: 1.5;
}
```

I would love being able to define my line height as `calc(1.5 * (0.9rem + 0.5vw))` to show the horizontal grid lines.
